'''
@author:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fibonacci(limit):
    a=1
    b=2
    fib=2
    sum=0

    while(fib<limit):
        if(fib%2==0):
            sum=sum+fib

        tmp=a+b
        a=b
        b=tmp
        fib=b

    return sum




def main():
    _limit=int(input("Enter the limit: "))
    _sum=fibonacci(_limit)
    print("The sum of even fibonacci number below "+str(_limit)+" = "+str(_sum))

if __name__ == '__main__':
    main()
